<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="COS-3572253-L1" name="scenarios.GEO.testcase01" tests="1" failures="0" timestamp="21 May 2019 19:55:33 GMT" time="21.464" errors="1">
  <testcase name="TC_01" time="21.464" classname="scenarios.GEO.testcase01">
    <error type="java.sql.SQLRecoverableException" message="IO Error: JNDI Package failure javax.naming.CommunicationException: oid.inf.fedex.com:3060 [Root exception is java.net.ConnectException: Connection timed out: connect]">
      <![CDATA[java.sql.SQLRecoverableException: IO Error: JNDI Package failure javax.naming.CommunicationException: oid.inf.fedex.com:3060 [Root exception is java.net.ConnectException: Connection timed out: connect]
at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:743)
at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:666)
at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:32)
at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:566)
at java.sql.DriverManager.getConnection(DriverManager.java:664)
at java.sql.DriverManager.getConnection(DriverManager.java:247)
at Utils.DbConnect.getResultSetFor(DbConnect.java:66)
at scenarios.GEO.testcase01.TC_01(testcase01.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: oracle.net.ns.NetException: JNDI Package failure javax.naming.CommunicationException: oid.inf.fedex.com:3060 [Root exception is java.net.ConnectException: Connection timed out: connect]
at oracle.net.jndi.JndiAttrs.<init>(JndiAttrs.java:169)
at oracle.net.resolver.AddrResolution.<init>(AddrResolution.java:214)
at oracle.net.ns.NSProtocol.connect(NSProtocol.java:207)
at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1452)
at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:496)
... 32 more
]]>
    </error>
  </testcase> <!-- TC_01 -->
</testsuite> <!-- scenarios.GEO.testcase01 -->
