<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SYN-FLX-001" name="scenarios.LOC.OpToOpMatchingPost" tests="34" failures="0" timestamp="30 Jan 2020 15:11:23 GMT" time="55.610" errors="4">
  <testcase name="TC_13" time="0.525" classname="scenarios.LOC.OpToOpMatchingPost">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at scenarios.LOC.OpToOpMatchingPost.testDataFields(OpToOpMatchingPost.java:3044)
	at scenarios.LOC.OpToOpMatchingPost.TC_13(OpToOpMatchingPost.java:1029)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </error>
  </testcase> <!-- TC_13 -->
  <testcase name="TC_01" time="4.969" classname="scenarios.LOC.OpToOpMatchingPost"/>
  <testcase name="TC_33" time="0.169" classname="scenarios.LOC.OpToOpMatchingPost">
    <error type="org.testng.SkipException" message="Execution skipped as per test flag set">
      <![CDATA[org.testng.SkipException: Execution skipped as per test flag set
	at scenarios.LOC.OpToOpMatchingPost.TC_33(OpToOpMatchingPost.java:2846)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </error>
  </testcase> <!-- TC_33 -->
  <testcase name="TC_06" time="1.311" classname="scenarios.LOC.OpToOpMatchingPost"/>
  <testcase name="TC_08" time="2.040" classname="scenarios.LOC.OpToOpMatchingPost"/>
  <testcase name="TC_02" time="1.688" classname="scenarios.LOC.OpToOpMatchingPost"/>
  <testcase name="TC_12" time="1.306" classname="scenarios.LOC.OpToOpMatchingPost"/>
  <testcase name="TC_16" time="1.427" classname="scenarios.LOC.OpToOpMatchingPost"/>
  <testcase name="TC_23" time="1.303" classname="scenarios.LOC.OpToOpMatchingPost"/>
  <testcase name="TC_11" time="1.343" classname="scenarios.LOC.OpToOpMatchingPost"/>
  <testcase name="TC_18" time="1.322" classname="scenarios.LOC.OpToOpMatchingPost"/>
  <testcase name="TC_32" time="1.890" classname="scenarios.LOC.OpToOpMatchingPost"/>
  <testcase name="TC_07" time="1.457" classname="scenarios.LOC.OpToOpMatchingPost"/>
  <testcase name="TC_03" time="1.649" classname="scenarios.LOC.OpToOpMatchingPost"/>
  <testcase name="TC_24" time="2.428" classname="scenarios.LOC.OpToOpMatchingPost"/>
  <testcase name="TC_30" time="3.840" classname="scenarios.LOC.OpToOpMatchingPost"/>
  <testcase name="TC_04" time="1.623" classname="scenarios.LOC.OpToOpMatchingPost"/>
  <testcase name="TC_05" time="0.437" classname="scenarios.LOC.OpToOpMatchingPost">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at scenarios.LOC.OpToOpMatchingPost.testDataFields(OpToOpMatchingPost.java:3044)
	at scenarios.LOC.OpToOpMatchingPost.TC_05(OpToOpMatchingPost.java:420)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </error>
  </testcase> <!-- TC_05 -->
  <testcase name="TC_14" time="1.375" classname="scenarios.LOC.OpToOpMatchingPost"/>
  <testcase name="TC_22" time="1.210" classname="scenarios.LOC.OpToOpMatchingPost"/>
  <testcase name="TC_26" time="1.944" classname="scenarios.LOC.OpToOpMatchingPost"/>
  <testcase name="TC_27" time="1.991" classname="scenarios.LOC.OpToOpMatchingPost"/>
  <testcase name="TC_21" time="1.200" classname="scenarios.LOC.OpToOpMatchingPost"/>
  <testcase name="TC_10" time="1.329" classname="scenarios.LOC.OpToOpMatchingPost"/>
  <testcase name="TC_29" time="1.901" classname="scenarios.LOC.OpToOpMatchingPost"/>
  <testcase name="TC_09" time="1.247" classname="scenarios.LOC.OpToOpMatchingPost"/>
  <testcase name="TC_17" time="1.383" classname="scenarios.LOC.OpToOpMatchingPost"/>
  <testcase name="TC_20" time="1.308" classname="scenarios.LOC.OpToOpMatchingPost"/>
  <testcase name="TC_25" time="2.376" classname="scenarios.LOC.OpToOpMatchingPost"/>
  <testcase name="TC_31" time="2.019" classname="scenarios.LOC.OpToOpMatchingPost"/>
  <testcase name="TC_34" time="0.185" classname="scenarios.LOC.OpToOpMatchingPost">
    <error type="org.testng.SkipException" message="Execution skipped as per test flag set">
      <![CDATA[org.testng.SkipException: Execution skipped as per test flag set
	at scenarios.LOC.OpToOpMatchingPost.TC_34(OpToOpMatchingPost.java:2959)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </error>
  </testcase> <!-- TC_34 -->
  <testcase name="TC_15" time="2.058" classname="scenarios.LOC.OpToOpMatchingPost"/>
  <testcase name="TC_28" time="1.981" classname="scenarios.LOC.OpToOpMatchingPost"/>
  <testcase name="TC_19" time="1.376" classname="scenarios.LOC.OpToOpMatchingPost"/>
</testsuite> <!-- scenarios.LOC.OpToOpMatchingPost -->
